version: '3.8'

services:
  data-collector:
    build:
      context: .
      dockerfile: Dockerfile.etl
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    ports:
      - "8888:8888"

volumes:
  mongodb_data:
    driver: local

networks:
  py-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16